title: Geoffrey Ellis Flutes
tagline: Contemporary World Flute Store

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
source:             ./_jekyll
destination:        ./_site

baseurl:            ""
url:                http://ellisflutes.com
timezone:           America/Los_Angeles

collections:
  # Products Setup #
  products:
    output: true
    permalink: /collections/:categories/products/:slug

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product
