title: Geoffrey Ellis Flutes
tagline: Contemporary World Flute Store

# Dependencies
markdown:           kramdown
#Syntax Highlighter
#highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
source:             ./_jekyll
destination:        ./_site

baseurl:            ""
url:                https://ellisflutes2017.netlify.com
timezone:           America/Los_Angeles

collections:
  # Products Setup #
  products:
    output: true
    permalink: /collections/:categories/products/:slug
  world_flutes:
    output: true
    permalink: /world-flutes/:slug

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: "/blog/:title"
  - scope:
      path: ""
      type: products
    values:
      layout: product
  - scope:
      path: ""
      type: world_flutes
    values:
      layout: world_flute

slideshow_image_ids:
  - MixedHeadjoints_fblwql
  - qdadbhdiiyvucpimpcqa
  - jukxcq1gd7cmy8klpciz
  - h9k6bnq2yba9otelwr0q
