title: Geoffrey Ellis Flutes
tagline: Contemporary World Flute Store

permalink: pretty

url: https://www.ellisflutes.com
api_url: https://admin-beta.ellisflutes.com
timezone: America/Los_Angeles

collections:
  # Products Setup #
  products:
    output: true
    permalink: /collections/:categories/products/:slug
#  ja_products:
#    output: true
#    permalink: /ja/collections/:categories/products/:slug
#    relative_directory: '_products'
  world_flutes:
    output: true
    permalink: /world-flutes/:slug
  galleries:
    output: true
    permalink: /galleries/:slug
#  ja_world_flutes:
#    output: true
#    permalink: /ja/world-flutes/:slug
#    relative_directory: '_world_flutes'

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: "/blog/:title"
  - scope:
      path: ""
      type: products
    values:
      layout: product
      lang: en
  - scope:
      path: ""
      type: galleries
    values:
      layout: gallery
      lang: en
  - scope:
      path: ""
      type: world_flutes
    values:
      layout: world_flute
      lang: en
  - scope:
      path: ""
      type: ja_products
    values:
      layout: product
      lang: ja
  - scope:
      path: ""
      type: ja_world_flutes
    values:
      layout: world_flute
      lang: ja

slideshow_image_ids:
  - ellisflutes2018/SquareShak1
  - ellisflutes2018/SquareShak2
  - MixedHeadjoints_fblwql
  - qdadbhdiiyvucpimpcqa
  - ellisflutes2018/IrishFlute1
  - ellisflutes2018/Essential_Cropped
  - jukxcq1gd7cmy8klpciz
  - ellisflutes2018/IrishFlute2
